#use: docker compose up -d

version: '3'

services:
  postgres:
    container_name: letsmeet_backend_db
    image: postgres:16.3-alpine3.19
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=letsmeet
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

networks:
  bridge:


volumes:
  postgres:
