version: '3'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=LetsMeet
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=!23Haslo

  backend:
    image: letsmeet
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5010:5010"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Username=postgres;Password=!23Haslo;Database=LetsMeet"
    depends_on:
      - postgres
        
  frontend:
    image: letsmeet-web
    build:
      context: ./LetsMeetWeb
      dockerfile: Dockerfile
    ports:
      - "4200:80" 
    depends_on:
      - backend
